### PR TITLE
Setup ESlint with Prettier

### PR DESCRIPTION
**Pull request by Ron-Lavi**
Added the following changes:
- downgrade to use React 16.14.0, same as Foreman
- Ignore lock files (Gemfile.lock, package-lock.json, yarn.lock)
- Added eslint with prettier (using 'eslint:recommended', 'plugin:react/recommended', 'plugin:prettier/recommended')
- Added CI with ESlint

### CODE REVIEW

**Comment by Ron-Lavi** [comment]
@LiorKGOW The CI will work only after we merge this PR.
@mariaaga I believe we should add it to your repo as well :)

**Comment by Ron-Lavi** [comment]
Successful build in https://github.com/Ron-Lavi/My-Guitar-Store/actions/runs/3355650694/jobs/5560076248

**Comment by LiorKGOW** [comment]
> @LiorKGOW The CI will work only after we merge this PR. @MariaAga I believe we should add it to your repo as well :)

I can work on it 👍🏼 @Ron-Lavi

**Comment by LiorKGOW** [comment]
LGTM Thanks! @Ron-Lavi 
This PR can be merged in my opinion

**Review by LiorKGOW — APPROVED** [review]
merging this PR to main 👍🏼 
Thanks @Ron-Lavi

**Pull request merged**
